services:

  frontend:
    build:
      context: .
    container_name: luxora-frontend
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8000
    ports:
      - "3000:3000"
    depends_on:
      - product-service

  product-service:
    build:
      context: ./product-service
    container_name: luxora-product-service
    ports:
      - "8000:8000"

  cart-service:
    build:
      context: ./cart-service
    container_name: luxora-cart-service
    ports:
      - "5000:5000"