name: LUXORA CI

on:
  push:
    branches:
      - main
      - devops-capstone
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  frontend:
    name: Frontend Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_PRODUCT_API=http://localhost:8000
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

  cart-service:
    name: Cart Service Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cart service
        uses: docker/build-push-action@v6
        with:
          context: ./cart-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cart-service:latest
            ghcr.io/${{ github.repository }}/cart-service:${{ github.sha }}

  product-service:
    name: Product Service Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push product service
        uses: docker/build-push-action@v6
        with:
          context: ./product-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product-service:latest
            ghcr.io/${{ github.repository }}/product-service:${{ github.sha }}